"""initial_clean_schema

Revision ID: 4381d9aa6b5d
Revises: b8e666b303c8
Create Date: 2026-06-03 21:31:09.734469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4381d9aa6b5d'
down_revision: Union[str, Sequence[str], None] = 'b8e666b303c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_webhook_events_event_type'), 'stripe_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_id'), 'stripe_webhook_events', ['id'], unique=False)
    op.create_table('users',
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('monthly_token_quota', sa.Integer(), nullable=False),
    sa.Column('monthly_spend_quota_usd', sa.Float(), nullable=False),
    sa.Column('monthly_tokens_used', sa.Integer(), nullable=False),
    sa.Column('monthly_spend_used_usd', sa.Float(), nullable=False),
    sa.Column('monthly_request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_table('admin_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audits_action'), 'admin_audits', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audits_created_at'), 'admin_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audits_entity_type'), 'admin_audits', ['entity_type'], unique=False)
    op.create_index(op.f('ix_admin_audits_id'), 'admin_audits', ['id'], unique=False)
    op.create_index(op.f('ix_admin_audits_user_id'), 'admin_audits', ['user_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('best_practices_score', sa.Integer(), nullable=True),
    sa.Column('crawl_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lighthouse_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gpt_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_index(op.f('ix_audits_status'), 'audits', ['status'], unique=False)
    op.create_index(op.f('ix_audits_url'), 'audits', ['url'], unique=False)
    op.create_index(op.f('ix_audits_user_id'), 'audits', ['user_id'], unique=False)
    op.create_table('generated_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('css', sa.Text(), nullable=True),
    sa.Column('js', sa.Text(), nullable=True),
    sa.Column('generated_url', sa.String(length=1000), nullable=True),
    sa.Column('gpt_model', sa.String(length=100), nullable=True),
    sa.Column('gpt_tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('gpt_tokens_completion', sa.Integer(), nullable=True),
    sa.Column('gpt_tokens_total', sa.Integer(), nullable=True),
    sa.Column('gpt_cost_usd', sa.Float(), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_sites_created_at'), 'generated_sites', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_sites_generation_status'), 'generated_sites', ['generation_status'], unique=False)
    op.create_index(op.f('ix_generated_sites_gpt_cost_usd'), 'generated_sites', ['gpt_cost_usd'], unique=False)
    op.create_index(op.f('ix_generated_sites_gpt_model'), 'generated_sites', ['gpt_model'], unique=False)
    op.create_index(op.f('ix_generated_sites_gpt_tokens_total'), 'generated_sites', ['gpt_tokens_total'], unique=False)
    op.create_index(op.f('ix_generated_sites_id'), 'generated_sites', ['id'], unique=False)
    op.create_index(op.f('ix_generated_sites_user_id'), 'generated_sites', ['user_id'], unique=False)
    op.create_table('plan_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('can_publish', sa.Boolean(), nullable=False),
    sa.Column('can_use_custom_domain', sa.Boolean(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.Column('max_sites', sa.Integer(), nullable=False),
    sa.Column('max_ai_credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_price_id'), 'subscriptions', ['stripe_price_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_table('usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ai_credits_used', sa.Integer(), nullable=True),
    sa.Column('sites_created', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('usage')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_price_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('plan_features')
    op.drop_index(op.f('ix_generated_sites_user_id'), table_name='generated_sites')
    op.drop_index(op.f('ix_generated_sites_id'), table_name='generated_sites')
    op.drop_index(op.f('ix_generated_sites_gpt_tokens_total'), table_name='generated_sites')
    op.drop_index(op.f('ix_generated_sites_gpt_model'), table_name='generated_sites')
    op.drop_index(op.f('ix_generated_sites_gpt_cost_usd'), table_name='generated_sites')
    op.drop_index(op.f('ix_generated_sites_generation_status'), table_name='generated_sites')
    op.drop_index(op.f('ix_generated_sites_created_at'), table_name='generated_sites')
    op.drop_table('generated_sites')
    op.drop_index(op.f('ix_audits_user_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_url'), table_name='audits')
    op.drop_index(op.f('ix_audits_status'), table_name='audits')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_admin_audits_user_id'), table_name='admin_audits')
    op.drop_index(op.f('ix_admin_audits_id'), table_name='admin_audits')
    op.drop_index(op.f('ix_admin_audits_entity_type'), table_name='admin_audits')
    op.drop_index(op.f('ix_admin_audits_created_at'), table_name='admin_audits')
    op.drop_index(op.f('ix_admin_audits_action'), table_name='admin_audits')
    op.drop_table('admin_audits')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stripe_webhook_events_id'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_event_type'), table_name='stripe_webhook_events')
    op.drop_table('stripe_webhook_events')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('plans')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
