name: Deploy to VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~

            if [ ! -d "clean-project" ]; then
              git clone https://github.com/meDo544/clean-project.git
            fi

            cd clean-project
            git pull origin main

            docker-compose down || true
            docker-compose up -d --build
